wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1643821679
    t:
      1:
      - 5
      - 8
      3:
      - 14
      4: 3.7.12
      5: 0.12.10
      8:
      - 1
      - 5
lambda_l1:
  desc: null
  value: 0.1
lambda_l2:
  desc: null
  value: 0.2
learning_rate:
  desc: null
  value: 0.1
max_depth:
  desc: null
  value: -1
num_class:
  desc: null
  value: 4
num_leaves:
  desc: null
  value: 128
objective:
  desc: null
  value: multiclass
