wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1643813013
    t:
      1:
      - 5
      - 8
      3:
      - 14
      4: 3.7.12
      5: 0.12.10
      8:
      - 1
      - 5
